- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.991"
  hooks:
    - id: mypy

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-ast
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: name-tests-test

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
    - id: reorder-python-imports

# - repo: https://github.com/asottile/seed-isort-config
#   rev: v2.2.0
#   hooks:
#     - id: seed-isort-config
# - repo: https://github.com/timothycrosley/isort
#   rev: 5.11.1 # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
#   hooks:
#     - id: isort

# - repo: https://github.com/pycqa/flake8
#   rev: 4.0.1
#   hooks:
#     - id: flake8
#       additional_dependencies:
#         - flake8-bugbear
#         - flake8-comprehensions
#         - flake8-simplify

- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
      args: [--safe]
# - repo: local
#   hooks:
#     - id: pytest-check
#       name: pytest-check
#       entry: pytest
#       language: system
#       pass_filenames: false
#       always_run: true
